mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('resume.urls')),
]

from django.conf.urls.static import static
from django.conf import settings
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

resume/urls.py
from django.urls import path
from .views import *

app_name = 'resume'
urlpatterns = [
    path('', resume, name='resume'),
    path('portfolio/', portfolio, name='portfolio'),
    path('portfolio/<tag>/', TagPortfolioView.as_view(), name='portfolio_tag'),
]

resume/models.py
from django.db import models
from tagging.fields import TagField


class Portfolio(models.Model):
    title = models.CharField(max_length=50)
    text = models.TextField()
    # photo = models.ImageField(upload_to='portfolio-img/%Y/%m/%d', blank=False, default='portfolio-img/no_image.png')
    photo = models.ImageField(upload_to='portfolio-img', blank=True, null=True)
    githublink = models.URLField('Github URL', blank=True, null=True)
    servicelink = models.URLField('Service URL', blank=True, null=True)
    tag = TagField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title + " - " + self.created.strftime("%Y-%m-%d %H:%M") + " - " + self.photo.url

resume/views.py
from django.shortcuts import render, redirect
from .models import Portfolio
from tagging.views import TaggedObjectList


def resume(request):
    return render(request, 'resume/resume.html')


def portfolio(request):
    pfs = Portfolio.objects.all()
    return render(request, 'resume/portfolio.html', {'object_list': pfs})


class TagPortfolioView(TaggedObjectList):
    model = Portfolio
    template_name = 'resume/portfolio.html'

resume/templates/resume/portfolio.html
{% extends 'base.html' %}
{% block content %}

<!-- Page Heading -->
<div class="d-flex">
  <h1 class="my-4">Portfolio list</h1>
  <p class="ml-3 align-self-center">공부하면서 만든 습작들 업로드하는 공간</p>
</div>

<!-- Project -->
{% load static %}
{% for post in object_list %}
<div class="row bg-secondary text-white rounded p-4 mx-1 mb-3">
  <div class="col-md-7">
    <a href="#">
      <img class="img-fluid rounded mb-md-0" src="{{post.photo.url}}" alt="">
    </a>
  </div>
  <div class="col-md-5">
    <h3 class="text-white">{{post.title}}</h3>
    <p>{{post.text|linebreaksbr}}</p>
    <a class="btn btn-info m-1" href="{{post.githublink}}" target="_blank">View Github</a>
    {% if post.servicelink %}
    <a class="btn btn-info m-1" href="{{post.servicelink}}" target="_blank">Run Service</a>
    {% endif %}
  </div>
</div>
{% endfor %}

<div class="border border-secondary rounded align-self-center my-2 mx-1 p-3">
  {% load tagging_tags %}
  {% tag_cloud_for_model resume.Portfolio as tags %}
  {% for tag in tags %}
  <a class="pl-1" href="{% url 'resume:portfolio_tag' tag=tag.name %}">
    #{{tag.name}}</a>
  {% endfor %}
</div>

{% endblock %}

resume/templates/resume/resume.html
{% extends 'base.html' %}
{% block content %}

<div id="page-top">
  <div class="container-fluid p-0">
    {% load static %}
    <link href="https://fonts.googleapis.com/css?family=Saira+Extra+Condensed:500,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Muli:400,400i,800,800i" rel="stylesheet">
    <link href="{% static 'resume/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet">
    <link href="{% static 'resume/css/resume.min.css' %}" rel="stylesheet">
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary" id="sideNav">
      <a class="navbar-brand js-scroll-trigger" href="#page-top">
        <span class="d-block d-lg-none">Clarence Taylor</span>
        <span class="d-none d-lg-block">
          <img class="img-fluid img-profile rounded-circle mx-auto mb-2" src="{% static 'resume/img/profile.jpg' %}" alt="">
        </span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#about">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#experience">Experience</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#skills">Skills</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#interests">Interests</a>
          </li>
        </ul>
      </div>
    </nav>

    <section class="resume-section p-3 p-lg-5 d-flex d-column" id="about">
      <div class="my-auto">
        <h1 class="mb-0">Gyuyoung
          <span class="text-primary">Lee</span>
        </h1>
        <div class="subheading mb-5">Seoul, KOREA · 010-2101-9507 ·
          <a href="mailto:name@email.com">reemin@gmail.com</a>
        </div>
        <p class="lead mb-5">게임서비스 영역에서 플랫폼, 인프라 운영 업무를 했었습니다.
          AWS, GCP 클라우드 환경에 친숙합니다. docker, kubernertes 서비스 기술을 잘 활용할 수 있습니다.
          최근에는 nodejs 등 자바스크립트 기반 코딩을 주로 하고 있습니다. </p>
        <div class="social-icons">
          <a href="https://github.com/loveuns" target="_blank">
            <i class="fab fa-github"></i>
          </a>
          <a href="https://www.facebook.com/gyuyoung" target="_blank">
            <i class="fab fa-facebook-f"></i>
          </a>
          <a href="https://www.linkedin.com/in/gyuyoung-lee-68b05b61/" target="_blank">
            <i class="fab fa-linkedin-in"></i>
          </a>
        </div>
      </div>
    </section>

    <hr class="m-0" id="experience">

    <section class="resume-section p-3 p-lg-5 d-flex flex-column">
      <div class="my-auto">
        <h2 class="mb-5">Experience</h2>

        <div class="resume-item d-flex flex-column flex-md-row mb-5">
          <div class="resume-content mr-auto">
            <h3 class="mb-0">Development Manager</h3>
            <div class="subheading mb-3">EA Korea</div>
            <ul>
              <li>CI/CD pipeline : gitlab, docker, jenkins</li>
              <li>Cloud Infra : AWS LDT support</li>
              <li>Devops/Agile : jira kanban, hansoft</li>
            </ul>
          </div>
          <div class="resume-date text-md-right">
            <span class="text-primary">May 2017 - May 2018</span>
          </div>
        </div>

        <div class="resume-item d-flex flex-column flex-md-row mb-5">
          <div class="resume-content mr-auto">
            <h3 class="mb-0">Technical PM - Team Manager</h3>
            <div class="subheading mb-3">Wemade Entertainment</div>
            <ul>
              <li>파트너 SDK 제공 및 integration 기술지원</li>
              <li>게임서비스 infra 구축 - architecting, deploy on AWS/OnPremise</li>
            </ul>
          </div>
          <div class="resume-date text-md-right">
            <span class="text-primary">January 2014 - June 2016</span>
          </div>
        </div>

        <div class="resume-item d-flex flex-column flex-md-row mb-5">
          <div class="resume-content mr-auto">
            <h3 class="mb-0">Technical PM</h3>
            <div class="subheading mb-3">Naver</div>
            <ul>
              <li>퍼블리싱 플랫폼 연동 가이드 작성</li>
              <li>퍼블리싱 플랫폼 기획 - Hangane PUPPLE</li>
              <li>게임서비스 infra, platform, solution 관리</li>
            </ul>
          </div>
          <div class="resume-date text-md-right">
            <span class="text-primary">June 2008 - December 2013</span>
          </div>
        </div>

        <div class="resume-item d-flex flex-column flex-md-row">
          <div class="resume-content mr-auto">
            <h3 class="mb-0">Software Engineer</h3>
            <div class="subheading mb-3">KT Hitel</div>
            <ul>
              <li>게임런처 개발 (MFC, Win32)</li>
              <li>인증 시스템 개발</li>
              <li>BI 지표 서비스 개발 (MSSQL Analysis Services)</li>
            </ul>
          </div>
          <div class="resume-date text-md-right">
            <span class="text-primary">January 2006 - May 2008</span>
          </div>
        </div>

      </div>

    </section>

    <hr class="m-0">

    <section class="resume-section p-3 p-lg-5 d-flex flex-column" id="skills">
      <div class="my-auto">
        <h2 class="mb-5">Skills</h2>
        <div class="subheading mb-3">Programming Languages &amp; Tools</div>
        <ul class="list-inline dev-icons">
          <li class="list-inline-item"><i class="fab fa-html5"></i></li>
          <li class="list-inline-item"><i class="fab fa-css3-alt"></i></li>
          <li class="list-inline-item"><i class="fab fa-js-square"></i></li>
          <li class="list-inline-item"><i class="fab fa-node"></i></li>
          <li class="list-inline-item"><i class="fab fa-python"></i></li>
          <li class="list-inline-item">
            <h3>django</h3>
          </li>
        </ul>
        <div class="subheading mb-3">Service Technologies</div>
        <ul class="list-inline dev-icons">
          <li class="list-inline-item"><i class="fab fa-aws"></i></li>
          <li class="list-inline-item">
            <h3>GCP</h3>
          </li>
          <li class="list-inline-item"><i class="fab fa-docker"></i></li>
          <li class="list-inline-item">
            <h4>Kubernetes</h4>
          </li>
          <li class="list-inline-item"><i class="fab fa-jenkins"></i></li>
        </ul>
      </div>
    </section>

    <hr class="m-0">

    <section class="resume-section p-3 p-lg-5 d-flex flex-column" id="interests">
      <div class="my-auto">
        <h2 class="mb-5">Interests</h2>
        <p>AI 스피커와 클라우드 환경의 지원을 받으며 챗봇과 머신러닝 분야가 급격하게 발전하고 있습니다.
          똑똑해진 챗봇으로 혼자서도 구현할 수 있는 일이 정말 많아 보입니다. 그래서 몇 개 만들어 보려 합니다.
          챗봇을 잘 활용하기 위해 Node.js, 머신러닝을 잘 활용하기 위해 python 연습 중입니다.</p>
        <p class="mb-0">또한 흥미로운 Javascript 기반 기술을 탐색 중입니다. Angular, React, Vue, Jasmine, Webpack
        </p>
        <a class="btn btn-info mt-3" href="https://omega2lambda.wordpress.com/" target="_blank">요즘 뭘 공부했을까</a>
      </div>
    </section>

  </div>
</div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Gyuyoung</title>
    <link href="{% static 'resume/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'resume/css/1-col-portfolio.css' %}" rel="stylesheet">
</head>

<body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg bg-dark navbar-dark fixed-top">
        <div class="container">
            <a class="navbar-brand" href="/">Gyuyoung Lee</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{% url 'resume:resume' %}">Resume</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{% url 'resume:portfolio' %}">Portfolio
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <!-- Page Content -->
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>

    <!-- Footer -->
    <footer class="bg-dark py-3 mt-3">
        <div class="container">
            <p class="m-0 text-center text-white">이 페이지는 장고로 만들어져 동적 관리가 가능합니다</p>
            <p class="m-0 text-center text-white">Copyright &copy; Gyuyoung Lee 2018</p>
        </div>
    </footer>

    <script src="{% static 'resume/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'resume/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- resume -->
    <script src="{% static 'resume/vendor/jquery-easing/jquery.easing.min.js' %}"></script>
    <script src="{% static 'resume/js/resume.min.js' %}"></script>
</body>

</html>